### PR TITLE
EZP-25837: inaccessible/missing fonts on eZ Platform 2016.04

### PR DESCRIPTION
**Pull request by damianz5**
https://jira.ez.no/browse/EZP-25837

### CODE REVIEW

**Comment by damianz5** [comment]
ping @andrerom @bdunogier

**Comment by emodric** [comment]
Isn't just `s?` enough ? You don't need a capturing group :)

**Comment by damianz5** [comment]
yes, but `fonts?` could be misleading

**Comment by emodric** [comment]
Yes, could be :)

**Comment by andrerom** [comment]
> yes, but fonts? could be misleading

how so? Folks thinking it would be a literal `?` in the url? well... :)

**Comment by bdunogier** [comment]
I agree with @emodric, and was about to write the same remark. It's a regexp, it is nou meant to be a nice guy.

That aside +1.

**Comment by damianz5** [comment]
right, PR updated

**Comment by emodric** [comment]
@damianz5 Capturing group still left in `doc/nginx/ez_params.d/ez_prod_rewrite_params` :)

**Comment by andrerom** [comment]
Thanks @damianz5 

Also merged to ezplatform-demo 1.3 and master branch: https://github.com/ezsystems/ezplatform-demo/commit/2eb2201129989b14a1f0c3f1a6e7e19d4b0ac802

**Pull request closed without merging**
