### PR TITLE
Update symfony conflicting version

### PR DESCRIPTION
**Pull request by micszo**
Updates symfony conflicting version to 3.4.9.

### CODE REVIEW

**Comment by micszo** [comment]
@lserwatka PR created

**Comment by lserwatka** [comment]
Please merge up to master.

**Comment by micszo** [comment]
@lserwatka I don't permission in this meta repo :) (403, denied)

**Comment by lserwatka** [comment]
@micszo please try now

**Comment by micszo** [comment]
Done - it works now.

**Comment by emodric** [comment]
@micszo @lserwatka Can you explain a bit why 3.4.9 is in conflict now? Symfony 3.4.9 works fine per my tests.

**Comment by lserwatka** [comment]
@emodric we are experiencing errors after content publication, it was detected when our Bethat tests started failing, likely related to persistence cache. We are investigating it.

**Comment by emodric** [comment]
Can you point to failures on Travis or similar?

Anyway, this PR is not valid, because now it allows installing Symfony 3.4.7, which has an error about circular references. It should've been `3.4.7|3.4.9`

**Comment by lserwatka** [comment]
PR is valid for now. It is temp solution to let our test systems operate normally until we find resulution to the problem. @micszo might give you a link to failing build.

**Comment by micszo** [comment]
Here is a example of the faulty behaviour: http://recordit.co/Q6OWRDhQDa

And here example of failed build: https://travis-ci.org/ezsystems/ezplatform-admin-ui/builds/376249328?utm_source=github_status&utm_medium=notification

**Comment by emodric** [comment]
Thanks! :+1:

**Comment by emodric** [comment]
It looks like this broke it: https://github.com/symfony/symfony/pull/27007 and then this fixed it again: https://github.com/symfony/symfony/pull/27158

**Comment by alongosz** [comment]
Yes, it's very likely. When trying to do a quick debug I also had an impression `invalidateTags` doesn't work as expected. Thanks for finding this @emodric

**Pull request merged**
