### PR TITLE
Update INSTALL.md

### PR DESCRIPTION
**Pull request by mzbusiness**
I needed to set php memory_limit=256M , default value for php 5.4 is 128M and ezplatform::install runs out of memory

### CODE REVIEW

**Comment by andrerom** [comment]
could be on the command instead, like other places here

**Comment by bdunogier** [comment]
It is most likely caused by the container's compilation, not by the script itself (it doesn't do anything that really uses memory).

We usually add the option to the command line directly in the instructions, we might want to do it here as well.

**Comment by joaoinacio** [comment]
Nitpick: all composer command examples use `php -d memory_limit=-1 ...`, IMHO it would probably make sense to use the same value for consistency.
(That and the possibility of 256M not being sufficient in the future for some unknown reason)

**Comment by mzbusiness** [comment]
other issue :
after installing I got error :   request.CRITICAL: Uncaught PHP Exception eZ\Bundle\EzPublishCoreBundle\ApiLoader\Exception\InvalidRepositoryException: "Undefined repository ''. Did you forget to configure it in ezpublish_*.yml?" at ...

After googling I found this related issue , 
https://jira.ez.no/browse/EZP-24025

After running clear:cache --env prod , ezpublish worked

**Comment by mzbusiness** [comment]
by the way , running php -d memory_limit=-1 ...
also runs out of memory, only manage to pass it after using 'none'  in the last question

**Comment by bdunogier** [comment]
That's really odd... the only explanation I can see would be that the process that runs out of memory isn't the same one than the initial one. @lolautruche ?

**Comment by andrerom** [comment]
@mzbusiness Which --env did you use for install command?

**Comment by mzbusiness** [comment]
I use prod env

**Comment by andrerom** [comment]
Ok, so we don't clear enough cache in the install command then.

**Comment by andrerom** [comment]
Reproduced and hopefully fixed the cache issue: https://jira.ez.no/browse/EZP-24158

Remaining open question is why `-d memory_limit=-1` didn't work for you.

**Comment by andrerom** [comment]
Returning to this question, I'm going to guess the issue is because we / symfony implicit call another php process via `static::executeCommand`, so the use of `-d memory_limit=-1` is not carried on to the sub process.

Two options:
- find a way to pass it on to sub process
- remove use of `-d memory_limit=-1` and rather accept this PR.

**Comment by andrerom** [comment]
Opened PR against Symfony: https://github.com/symfony/symfony/pull/15153

However since this will take some time to trickle into Symfony releases, and also Composer releases which bundles this component, and thus blocks the local file in vendor form being used, I vote for also merging this for now.

+1

**Comment by bdunogier** [comment]
Given this analysis, yes, this patch is a good workaround.

+1 then.

**Comment by andrerom** [comment]
Thanks for the PR @mzbusiness, all clear, all merged :)

**Pull request merged**
