### PR TITLE
Added missing behatbundle behat.yml to behat.yml.dist

### PR DESCRIPTION
**Pull request by miguelcleverti**
As discussed in the [travis fix PR](https://github.com/ezsystems/BehatBundle/pull/42) added the missing behat.yml to behat.yml.dist

### CODE REVIEW

**Comment by miguelcleverti** [comment]
@bdunogier

**Comment by yannickroger** [comment]
Got problems with your keyboard or your finger @miguelcleverti ? :)
No PR description, not even "ping" in front of Bertrand's name.

**Comment by miguelcleverti** [comment]
The tests are failing most likely because in BehatBundle there is still a reference to `EzPublishKernel`: I guess we have sort of a circular dependency between these two PRs (https://github.com/ezsystems/BehatBundle/pull/42) @bdunogier

**Comment by miguelcleverti** [comment]
Changed the sub-behat.yml into behat_suites.yml. See https://github.com/ezsystems/BehatBundle/pull/42

**Comment by andrerom** [comment]
+1 *(but ideally needs merges to the other repositories just before so merge here will pass, if not we will know that further changes might be needed)*

**Comment by bdunogier** [comment]
Other repos merged, triggering this build to see if it passes.

**Comment by bdunogier** [comment]
Merged the BehatBundle one, restarted build.

**Comment by bdunogier** [comment]
Al green, superb.

**Pull request merged**
