### PR TITLE
[Composer] Remove conflict with Symfony 3.4.12

### PR DESCRIPTION
**Pull request by andrerom**
Issue has been solved in: https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/releases/tag/1.3.16

If travis agrees I guess we can merge this up.

### CODE REVIEW

**Comment by andrerom** [comment]
Errors like:
```
eZ\Bundle\EzPublishRestBundle\Features\Context\RestContext::usePermissionsOfRole()
      eZ\Publish\Core\Base\Exceptions\UnauthorizedException: User does not have access to 'read' 'role' in vendor/ezsystems/ezpublish-kernel/eZ/Publish/Core/Repository/RoleService.php:784
```
So I think we hold back on allowing 3.4.12 until we know what this is and can solve it.

**Comment by lserwatka** [comment]
We ship with 3.4.11. I don't want to risk.

**Comment by emodric** [comment]
I'm also seing errors with `sudo` and 3.4.12, for example, `User does not have access to 'read' 'content' with: contentId '14''`

**Comment by andrerom** [comment]
Closing we need 3.4.13 out for fix:
https://github.com/symfony/symfony/pull/27776

**Pull request closed without merging**
