### PR TITLE
Pin selenium docker image version to 2.53.1

### PR DESCRIPTION
**Pull request by miguelcleverti**
Selenium 3 causes issue with behat because it uses the new marionette/geckodriver(see https://github.com/mozilla/geckodriver) which are not yet fully implemented. For now the version should be pinned to the previous one

### CODE REVIEW

**Comment by miguelcleverti** [comment]
ping @andrerom @micszo

**Comment by andrerom** [comment]
In retrospective this should have been done against 1.5 branch

**Comment by lserwatka** [comment]
@andrerom we should revert this and open against 1.5 then merge up to master and then to 1.5/master ezstudio and 1.5/master ezstudio-demo. WDT?

**Comment by andrerom** [comment]
to late, I cherry picked it to 1.5 and merged that into master, I suggest you do the same, but in your case you can also merge up changes from master here _(optionally you can do that later also, as it's only a merge commit with effectively no changes given the change was already there)_.

**Pull request merged**
