### PR TITLE
[Travis/Composer] Remove composer.lock and prefer ip4 on travis to av…

### PR DESCRIPTION
**Pull request by andrerom**
…oid packagist issues

ref: https://github.com/composer/composer/issues/4142#issuecomment-117648869

### CODE REVIEW

**Comment by michalpipa** [comment]
Big :+1: for removing composer.lock

**Comment by andrerom** [comment]
Job just restarted, should pass now with fix from @lolautruche and @bdunogier so we can get rid of composer.lock so we can go back to testing master for behat tests.

**Comment by lolautruche** [comment]
+1

**Comment by bdunogier** [comment]
+1

**Comment by andrerom** [comment]
Thanks, @michalpipa please cherry-pick this on studio as well :)

**Comment by michalpipa** [comment]
@andrerom Great!

**Pull request merged**
