### PR TITLE
EZP-31007: Replaced ezpublish-kernel with ezplatform-kernel

### PR DESCRIPTION
**Pull request by alongosz**
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [EZP-31007](https://jira.ez.no/browse/EZP-31007)
| **Type**                                   | improvement
| **Target eZ Platform version** | `v3.0`
| **BC breaks**                          | **no**
| **Tests pass**                          | [yes](https://travis-ci.org/github/ezsystems/ezplatform/builds/664823684)
| **Doc needed**                       | yes

### Summary

This PR installs `ezplatform-kernel` instead of `ezpublish-kernel`. `ezplatform-kernel` is a fork of `ezpublish-kernel`. This is one of the long overdue steps related to Product re-branding.

eZ Platform Kernel will be released as `v1.0.0`.

### BC

Don't worry :) Right now this is a cosmetic change. Namespaces are the same. We will gradually, trying to keep BC, introduce new namespaces later on (rather after 3.0 final).

It also still provides `ezpublish` extension as well (`ezplatform` is offered by `EzPlatformCoreBundle`).

### Notes

PR contains out of scope changes to `composer.json`, because composer sorts packages alphabetically.

### Other advantages of this step

The main issue right now is composer memory. With a completely new package w/o old eZ Publish tags, memory usage during install should be reduced.

### Merge up procedure (for eZ Systems maintainers)

`ezplatform-kernel` is a fork of `ezpublish-kernel` and it supports eZ Platform 3.0 or higher. It means that bug fixes still go into `ezpublish-kernel` and then are to be merged horizontally from `ezpublish-kernel:master` to `ezplatform-kernel:master`.

Merge up procedure, starting from the lowest supported version, is as follows:
1. Merge `ezpublish-kernel:6.13` into `7.5`,
2. Merge `ezpublish-kernel:7.5` into `master`,
3. Merge `ezpublish-kernel:master` into **`ezplatform-kernel:master`**.

**TODO**:
- [x] Drop TMP commit
- [x] See if anything fails and needs to be adjusted (related to test setup).
- [ ] Ask for code review.
- [ ] Drop `ezsystems:ezp-31007-ezplatform-kernel` branch after running tests.

### CODE REVIEW

**Comment by emodric** [comment]
This means that packages cannot support eZ kernel 7.5 and 8.0 at the same time without major version bump, which is not possible nor practical sometimes.

So now I have to jump through hoops to support both kernels. And you still have `ezplatform-kernel` v1, `ezplatform-admin-ui` v2 and eZ Platform v3, which is a mess.

**Comment by alongosz** [comment]
> This means that packages cannot support eZ kernel 7.5 and 8.0 at the same time

It's technically not possible due to Symfony changes anyway.

> which is a mess.

The mess is when you try to support everything in a single package version. SemVer was created for a reason.

**Comment by emodric** [comment]
> It's technically not possible due to Symfony changes anyway.

Yes it is. We have packages supporting both without issues.

> The mess is when you try to support everything in a single package version. SemVer was created for a reason.

So if someone told you to bump a major version of eZ kernel because a single package decided to break the internet, would you do it? Or do you have a roadmap for your releases?

Others have roadmap too, and bumping major versions is not always feasible.

What I meant by the mess was, you're trying to "unify" naming and branding across packages, while your versions are a mess to begin with and are not unified at all.

**Comment by lserwatka** [comment]
We have to complete process of rebranding. And major version product release is only opportunity for us. We will proceed with this change. We have not made any change since 8 years. It is supper confusing for all our non-paying and paying customers that kernel is named ezpublish. It is hurting our enablement process and eduction for new users.

**Comment by ilukac** [comment]
Making the new ezplatform-kernel v1 has absolutely no sense.  If you are doing this then it can only make sense to version it inline with ez platform: v3. 

Otherwise it doesn't simplify anything, the confusion will stay the same, just be different :)

**Comment by ilukac** [comment]
And btw ezplatfform-admin-ui is currently ver2 ;)

**Comment by emodric** [comment]
> We will proceed with this change.

Didn't think otherwise...

> We have not made any change since 8 years.

So what?

> It is supper confusing for all our non-paying and paying customers that kernel is named ezpublish. It is hurting our enablement process and eduction for new users.

Well, there are many more confusing things about the whole stack, I doubt the fact that the kernel is named ezpublish plays a major role in confusion.

**Comment by lserwatka** [comment]
Every package can have different version, it is not a problem at all that admin-ui has version 2.0. No need to make use sarcasm here or making jokes. ezplatform-kernel is is a new package so restarting versioning makes a lot of sense. Versioning was broken since very beginning.

**Comment by emodric** [comment]
> No need to make use sarcasm here or making jokes.

I'm not using sarcasm or jokes. I'm stating facts.

> Versioning was broken since very beginning.

So why don't you fix it now, that you have the chance?

**Comment by lserwatka** [comment]
In early days of eZ Platform we have been following versioning synchronised with Product version. However this does not work at all in a long run for a product vendor like we are. Several issues: 

1. we where making ghost releases by increasing version on packages where there was no single change.
2. New packages had to start from version 1.5 instead of version 1.0. What breaks entire purpose of semver. 

Let's think about the future. Let's say we are on the version 3.0.0:
In composer.json we got ezplatform-kernel:~1.0.0. We got a bug, that requires change in DB schema. Since update is a BC break and potentially can make a lot of trouble (real use case in 2.5.9 LTS with language_mask). We are making a fix in eZ Platform 3.0.1 with composer.json set on ezplatform-kernel: ~1.1.0. It is not a perfect semver but compromise.

Major benefit is that when you do composer update, you don't have to worry that something will break because we did something. It is your decision that you want to upgrade product to 3.0.1 and you need to study release note and follow it carefully. This is a real life case that was hitting us and our customers.

We don't have any mess with packages versioning, each package follows its own life and product is a compilation of different packages following semvers. So argument about version mess is not valid at all.

**Comment by emodric** [comment]
The number of times I had to explain that kernel version is not the platform version and vice versa, coupled with the fact that eZ does not have great record of following semver, makes your point moot.

Having kernel 1.0 and platform 3.0 will produce the exact same mess as kernel 8 and platform 3.

**Comment by lserwatka** [comment]
So problem is only with one package where in real life developers would prefer to think about kernel version same as product version? Fixing all packages is impossible, we have been there already and this does not work as I explained.

**Comment by emodric** [comment]
Problem is with the central packages. platform, kernel, admin ui... Nobody cares that ez support tools is at version 1.0 and platform is at v3. But central packages should be synced.

**Comment by lserwatka** [comment]
Don't you think this will make more mess? Having it synced with major product version. Like 3.x.y, 4.x.y. W can't lock it. So it might happen that in Product version 3.0.1 we will have kernel and admin ui 3.1.0. I have a feeling that this won't solve any problem but will cause more confusion. Speaking from package perspective where it has independent versioning is much cleaner.

**Comment by lserwatka** [comment]
We understand that we are judged from Symfony perspective where every package has same version, which is super convenient but they have monorepo. This does not apply to product like ours. Our product is compilation of many independent packages. This is the perspective we have.

**Comment by emodric** [comment]
> So it might happen that in Product version 3.0.1 we will have kernel and admin ui 3.1.0.

Why would you? Bump to 3.1.0 would imply having a new feature, which goes against semver if you consider eZ Platform would be 3.0.1 and not 3.1.0.

Anyway, this discussion drifted away from the more important issue: renaming the package.

For anyone reading this, requiring `ezsystems/ezplatform-admin-ui` in version `^1.5 || ^2.0` will allow packages support all three kernel packages without issues (ezpublish kernel v7, ezpublish kernel v8, ezplatform kernel v1), although it is really silly for having to do this.

**Comment by lserwatka** [comment]
There won't be any kernel v8. v8 will become v1 as ezplatform-kernel.

**Comment by emodric** [comment]
There's already kernel v8 in beta versions.

**Comment by lserwatka** [comment]
Yes, but will be replaced with v1 from ezplatfrom-kernel. So we will never release v8.

**Comment by emodric** [comment]
Yes, in the meantime the tagged beta versions can be installed.

**Comment by lserwatka** [comment]
Yes, but don't care about it. RC1 will have ezplatfrom-kernel v1 and we will only support 6.13 (1.13 LTS) and 7.5  (2.5 LTS). We will never release stable v8. eZ Platform 3.0.0 will use package ezplatform-kernel 1.0. What makes a lot of sense.

**Comment by lserwatka** [comment]
We will actually release eZ Platform 3.0.0-rc1 on Monday with new kernel package.

**Comment by emodric** [comment]
Okay, you've made your point. I will edit my original post. Jeez.

**Comment by alongosz** [comment]
Merging to unblock Behat tests in dependencies. QA will be done afterwards.

**Pull request merged**
