### PR TITLE
[Composer] Add BazingaJsTranslationBundle

### PR DESCRIPTION
**Pull request by andrerom**
As needed by https://github.com/ezsystems/PlatformUIBundle/pull/525

### CODE REVIEW

**Comment by andrerom** [comment]
@yannickroger I guess this PR might have one todo, namely calling command to generate translation strings for all translations *(given UI can be in anything not necessarily in symfony config)* via composer.json post install/update cmd.

**Comment by dpobel** [comment]
Just updated to BazingaJsTranslationBundle to 2.6

**Comment by dpobel** [comment]
ping @andrerom @glye

**Comment by andrerom** [comment]
+1 _(I can't approve my own PR)_

**Pull request merged**
