### PR TITLE
Added symfony/thanks dependency

### PR DESCRIPTION
**Pull request by javiereguiluz**
*This is my first PR to this project. I'm sorry if I did something wrong or not followed some required process.*

I propose to add `symfony/thanks` as a dependency of this project. [Symfony Thanks](https://symfony.com/blog/say-thanks-to-the-libraries-you-depend-on) allows users to say thanks to the libraries used in their projects. Despite its name, it's not a "Symfony thing", but a "PHP thing". It's already been included in Symfony, Laravel ([60de3a5](https://github.com/laravel/laravel/commit/60de3a5670c4a3bf5fb96433828b6aadd7df0e53)), Drupal (via Drupal Console [#3727](https://github.com/hechoendrupal/drupal-console/pull/3727)) and Akeneo PIM ([#7538](https://github.com/akeneo/pim-community-dev/pull/7538)).

Technically speaking, it's a tiny dependency that includes just a few lines of PHP code (all the work is done by Composer) and it doesn't affect the performance in any way (it's just a console command). The dependency doesn't execute anything unless the user explicitly wants to do that and types some command. 

A nice side effect of "saying thanks" is that the entire PHP community gets more recognition on GitHub. That could be the case for eZ too. I personally feel like you deserve many more GitHub stars in all your repos.

Thanks for your consideration!

### CODE REVIEW

**Comment by crevillo** [comment]
hi @javiereguiluz. glad to have you here! :)
For me is a +1.

**Comment by MarioBlazek** [comment]
+1 also

**Comment by robinmuilwijk** [comment]
Great PR @javiereguiluz , if this is added to the code, I'll be sure to promote it in our community. Thanks!

**Comment by andrerom** [comment]
@robinmuilwijk Merged, you can start promoting this once 2.1 is out, we aim to ship this in all flavors of the platform so everyone should be able to use it.

**Comment by javiereguiluz** [comment]
@andrerom thanks for merging, and thank you all for the support!

**Comment by emodric** [comment]
Great one @javiereguiluz !

**Pull request merged**
