### PR TITLE
EZS-1281: Adjust setup_from_external_repo.sh

### PR DESCRIPTION
**Pull request by damianz5**
Adjust setup_from_external_repo.sh in ezplatform meta

https://jira.ez.no/browse/EZS-1281

### CODE REVIEW

**Comment by lserwatka** [comment]
Once this is merge I will pull this to other repos.

**Comment by micszo** [comment]
@andrerom Could you confirm the list of occurrences listed in the Jira ticket? Do you know of any other cases that should be taken into account?

**Comment by andrerom** [comment]
Somewhat, but not sure without checking.

But script seems to be safe, it falls back to how it already behaves so don't see any issues with this now.

**Comment by micszo** [comment]
@andrerom I confirmed with @damianz5 this is ready, please merge. :)

**Comment by andrerom** [comment]
Thanks, merged and merged up to master.
So it can be merged further to studio repos now.

**Pull request merged**
