### PR TITLE
EZP-24579 updating INSTALL.md with the new url to call the application

### PR DESCRIPTION
**Pull request by StephaneDiot**
https://jira.ez.no/browse/EZP-24579

## Description

This PR only update the INSTALL.md to go with https://github.com/ezsystems/PlatformUIBundle/pull/283

### CODE REVIEW

**Comment by StephaneDiot** [comment]
ping @dpobel

**Comment by dpobel** [comment]
+1

**Comment by andrerom** [comment]
+1

**Comment by StephaneDiot** [comment]
Can't merge this one, Idont' have the permission on this repository. However I'm merging https://github.com/ezsystems/PlatformUIBundle/pull/283

**Pull request merged**
