### PR TITLE
WIP : Updated web config so settings can be injected via environment variables

### PR DESCRIPTION
**Pull request by vidarl**
This PR makes it easier to deal with provided vhost config autocratically  as values now can be injected using tools like envsubst instead having to do search&replace using regexp and sed etc...

### CODE REVIEW

**Comment by vidarl** [comment]
Todo:
 - Update readme ( nginx.rst )
 - Update apache vhost accordingly

**Comment by andrerom** [comment]
The problem with envsubst is that we can' define defaults, neither in template using ` ${variable-default}`, or in a script like I do in the [branch](https://github.com/ezsystems/ezplatform/tree/tmp_bash_vhost) where I'm trying to do the same for apache.

**Comment by bdunogier** [comment]
I personally don't really see the problem with using sed. It's what most container images do, and it's not that complicated.

**Comment by yannickroger** [comment]
Yeah, it's not like we have a 100 keys to be replaced.

**Comment by vidarl** [comment]
The problem with sed is that you explicitly have to mention all replacements. So if you want to replace PORT, BASEDIR + 10 other variables, you have write them all on the command line.

However, in AR's ```tmp_bash_vhost```  branch he anyway creates a script for doing the replacements. So then I am actually fine usinging sed ( or bash substitution which AR attempts to do )
But I initially misunderstood AR as I though he  he did not want to have a separate script to handle the substitution.

**Comment by andrerom** [comment]
> But I initially misunderstood AR as I though he he did not want to have a separate script to handle the substitution.

Actually you did not, ideally I wanted to avoid this, but not at the cost of making the template unreadable, and not at the cost of usability *(I consider having to define, and understand all env's, every time, not very usable)*.

**Comment by vidarl** [comment]
I'll close this PR and create a new one for nginx based on AR's tmp_bash_vhost branch

**Comment by vidarl** [comment]
FYI : new PR : https://github.com/ezsystems/ezplatform/pull/83/

**Pull request closed without merging**
