### PR TITLE
EZP-31875: Added firewall rules for JWT auth

### PR DESCRIPTION
**Pull request by bdunogier**
Required by:
- https://github.com/ezsystems/ezplatform-graphql/pull/86
- https://github.com/ezsystems/ezplatform-rest/pull/54

### CODE REVIEW

**Review by adamwojs — COMMENTED** [review]
Hi! Thanks for PR, but IMHO additional firewall should be enabled by user only if he/she really like to use JWT (as usually in case of security features)

**Comment by lserwatka** [comment]
@mnocon Travis is filing here.

**Comment by mnocon** [comment]
@lserwatka REST functional tests are failing with errors such as:
```
1) EzSystems\EzPlatformRestBundle\Tests\Functional\BookmarkTest::testCreateBookmark

Server error message (401): Unauthorized

The User does not have the 'create' 'content' permission with: parentLocationId '2', sectionId '1'
```
So probably related to this PR, maybe they should be adapted somehow when JWT is used, not sure.

**Comment by bdunogier** [comment]
> Hi! Thanks for PR, but IMHO additional firewall should be enabled by user only if he/she really like to use JWT (as usually in case of security features)

Maybe add them commented out then ?

> REST functional tests are failing
Hmm. I think it is because we rely on basic auth for functional tests.
@kmadejski should we add exclusion rules for the matcher when the request includes basic auth / Bearer token (and maybe session ?) auth ?

**Comment by kmadejski** [comment]
I second @adamwojs here. My idea from the beginning was that this is opt-in.

> Hmm. I think it is because we rely on basic auth for functional tests.
@kmadejski should we add exclusion rules for the matcher when the request includes basic auth / Bearer token (and maybe session ?) auth ?

And this is exactly one of the reasons why I want it as an opt-in, at least for now. If you know that you want to use it, then you enable it. I can hardly imagine that you would like to have both JWT & Session & maybe even basic auth enabled in the same time. 

Maybe for the future, we should consider JWT to be a first-choice for us, but as you know it would involve some changes in AdminUI and so on...

**Comment by adamwojs** [comment]
> Maybe add them commented out then ?

Yes, It's good idea.

**Comment by bdunogier** [comment]
Changed to comments, with a short line of explanation. Also fixed the typo, because `patform` is cute, not not very professional.

@mnocon talking about REST integration tests, do you think we could add one specific to JWT auth ? That would maybe enable JWT auth, login, and run a restricted API call ?

**Review by lserwatka — APPROVED** [review]

**Review by adamwojs — APPROVED** [review]

**Review by micszo — APPROVED** [review]

**Comment by lserwatka** [comment]
@mnocon could you merge it sideways?

**Comment by mnocon** [comment]
@lserwatka sure, merged
@bdunogier that's a good idea, I'll try a have a look at it soon

**Pull request merged**
