### PR TITLE
Fix indentation for the default_ttl config var

### PR DESCRIPTION
**Pull request by crevillo**
An easy one. Indetation is 4 spaces for all the file except for this part i'm changing now. Just in order to follow the same rule for everything.

ping @andrerom

### CODE REVIEW

**Comment by andrerom** [comment]
Does it also affect 1.13?

**Comment by crevillo** [comment]
yes, seems so. https://github.com/ezsystems/ezplatform/blob/1.13/app/config/ezplatform.yml#L39

**Comment by andrerom** [comment]
ok, then please rebase this for 1.13 and change base branch here, and we'll take care about conflicts when merging up.

**Comment by crevillo** [comment]
Done. let me know if i did it ok. no conflicts here...

**Pull request merged**
