### PR TITLE
[Composer] Update ezplatform-http-cache to 1.0 & symfony-tools to 1.1

### PR DESCRIPTION
**Pull request by andrerom**
This PR is for QA testing _(here and on EE repo)_ of the following 2.5 fixes::
- [EZP-31113](https://jira.ez.no/browse/EZP-31113): AssignSectionToSubtreeSignal is not handled by search and HTTP cache
   - Specifically https://github.com/ezsystems/ezplatform-http-cache/pull/106, solr fix is part of `1.7@dev` & `2.0@dev`
- [EZP-30562](https://jira.ez.no/browse/EZP-30562): As an Administrator I would like to use short HTTP cache tags
   - https://github.com/ezsystems/ezplatform-http-cache/pull/112
- [EZP-31350](https://jira.ez.no/browse/EZP-31350): Update Symfony Cache adapters to reduce Redis requirements & maintenance overhead
    - https://github.com/ezsystems/symfony-tools/pull/10

### CODE REVIEW

**Comment by micszo** [comment]
@andrerom I can't install these changes on EE, there is some conflict with ezplatform-rest:
```
Problem 1
    - ezsystems/ezplatform-http-cache v1.0.0-beta4 requires ezsystems/ezplatform-rest ^1.0 -> satisfiable by ezsystems/ezplatform-rest[1.0.x-dev, v1.0.0-beta1, v1.0.0-beta3, v1.0.0-beta4] but these conflict with your requirements or minimum-stability.
    - ezsystems/ezplatform-http-cache v1.0.0-beta3 requires ezsystems/ezplatform-rest ^1.0 -> satisfiable by ezsystems/ezplatform-rest[1.0.x-dev, v1.0.0-beta1, v1.0.0-beta3, v1.0.0-beta4] but these conflict with your requirements or minimum-stability.
    - ezsystems/ezplatform-http-cache v1.0.0-beta2 requires ezsystems/ezplatform-rest ^1.0 -> satisfiable by ezsystems/ezplatform-rest[1.0.x-dev, v1.0.0-beta1, v1.0.0-beta3, v1.0.0-beta4] but these conflict with your requirements or minimum-stability.
    - ezsystems/ezplatform-http-cache v1.0.0-beta1 requires ezsystems/ezplatform-rest ^1.0@beta -> satisfiable by ezsystems/ezplatform-rest[1.0.x-dev, v1.0.0-beta1, v1.0.0-beta3, v1.0.0-beta4] but these conflict with your requirements or minimum-stability.
    - ezsystems/ezplatform-http-cache-fastly 1.1.x-dev requires ezsystems/ezplatform-http-cache ~0.5 -> satisfiable by ezsystems/ezplatform-http-cache[0.9.x-dev, 0.8.x-dev].
    - ezsystems/ezplatform-http-cache-fastly v1.1.0 requires ezsystems/ezplatform-http-cache ~0.5 -> satisfiable by ezsystems/ezplatform-http-cache[0.9.x-dev, 0.8.x-dev].
    - ezsystems/ezplatform-http-cache-fastly v1.1.0-rc1 requires ezsystems/ezplatform-http-cache ~0.3 -> satisfiable by ezsystems/ezplatform-http-cache[0.9.x-dev, 0.8.x-dev].
    - ezsystems/ezplatform-http-cache-fastly v1.1.0-rc2 requires ezsystems/ezplatform-http-cache ~0.5 -> satisfiable by ezsystems/ezplatform-http-cache[0.9.x-dev, 0.8.x-dev].
    - ezsystems/ezplatform-http-cache-fastly v1.1.0-beta1 requires ezsystems/ezplatform-http-cache ~0.3 -> satisfiable by ezsystems/ezplatform-http-cache[0.9.x-dev, 0.8.x-dev].
    - ezsystems/ezplatform-http-cache-fastly v1.1.0-beta2 requires ezsystems/ezplatform-http-cache ~0.3 -> satisfiable by ezsystems/ezplatform-http-cache[0.9.x-dev, 0.8.x-dev].
    - ezsystems/ezplatform-http-cache-fastly v1.1.1 requires ezsystems/ezplatform-http-cache ~0.5 -> satisfiable by ezsystems/ezplatform-http-cache[0.9.x-dev, 0.8.x-dev].
    - ezsystems/ezplatform-http-cache-fastly v1.1.2 requires ezsystems/ezplatform-http-cache ~0.5 -> satisfiable by ezsystems/ezplatform-http-cache[0.9.x-dev, 0.8.x-dev].
    - ezsystems/ezplatform-http-cache-fastly v1.1.3 requires ezsystems/ezplatform-http-cache ~0.5 -> satisfiable by ezsystems/ezplatform-http-cache[0.9.x-dev, 0.8.x-dev].
    - ezsystems/ezplatform-http-cache-fastly 1.1.x-dev requires ezsystems/ezplatform-http-cache ~0.5 -> satisfiable by ezsystems/ezplatform-http-cache[0.9.x-dev, 0.8.x-dev].
    - Can only install one of: ezsystems/ezplatform-http-cache[1.0.x-dev, 0.9.x-dev].
    - Can only install one of: ezsystems/ezplatform-http-cache[1.0.x-dev, 0.8.x-dev].
    - Can only install one of: ezsystems/ezplatform-http-cache[1.0.x-dev, 0.9.x-dev].
    - Installation request for ezsystems/ezplatform-http-cache ^1.0@dev -> satisfiable by ezsystems/ezplatform-http-cache[1.0.x-dev, v1.0.0-beta1, v1.0.0-beta2, v1.0.0-beta3, v1.0.0-beta4].
    - Installation request for ezsystems/ezplatform-http-cache-fastly ^1.1@dev -> satisfiable by ezsystems/ezplatform-http-cache-fastly[1.1.x-dev, v1.1.0, v1.1.0-rc1, v1.1.0-rc2, v1.1.0-beta1, v1.1.0-beta2, v1.1.1, v1.1.2, v1.1.3].
```
Am I missing something?

**Comment by andrerom** [comment]
The conflict was`ezsystems/ezplatform-http-cache-fastly`. Works on my side after pushing fix, sorry for the blocker.
https://github.com/ezsystems/ezplatform-http-cache-fastly/commit/04dd380ab1c729baa5dfa0b0277bf0092274c4aa

**Comment by micszo** [comment]
I confirm installation works after the fix. 👍

**Comment by andrerom** [comment]
Some updates on http-cache:
- Requested by LS to be able to avoid the header overflow: https://github.com/ezsystems/ezplatform-http-cache/pull/116
- Old content tags are now mapped to new once to avoid duplicated tags when old tags are used by page-field-type and kernel (relation fields): https://github.com/ezsystems/ezplatform-http-cache/commit/746c8d723c8e751dda3c409fc4411bd05821caf5

**Comment by andrerom** [comment]
@micszo Yes given this is merged it's intended for 2.5.9 as well, was not 2.5.9-rc1 made from 2.5 branch?

**Comment by micszo** [comment]
ok, thanks! we will have rc2 :)

**Pull request merged**
