### PR TITLE
EZP-30098 [Travis] Implement solution for running tests in threads based on fastest

### PR DESCRIPTION
**Pull request by m-tyrala**
This PR introduces changes that load Fastest extension for behat multithreading.

Ticket: [EZP-30098](https://jira.ez.no/browse/EZP-30098)

Related PRs:
https://github.com/ezsystems/ezplatform-admin-ui/pull/812
https://github.com/ezsystems/ezplatform-page-builder/pull/305
https://github.com/ezsystems/ezplatform-form-builder/pull/138

### CODE REVIEW

**Comment by lserwatka** [comment]
@m-tyrala what is needed to merge this one?

**Comment by m-tyrala** [comment]
@lserwatka technically nothing, but we were thinking about finishing this after releasing version 2.5 when the situation will be less hectic

**Comment by m-tyrala** [comment]
@lserwatka ready to merge

**Comment by andrerom** [comment]
@lserwatka merged this to master as part of tag command merge

**Comment by lserwatka** [comment]
@andrerom OK, @m-tyrala you don't need to merge it up.

**Pull request merged**
