### PR TITLE
.platform.app.yaml: Update comment web→public

### PR DESCRIPTION
**Pull request by adriendupuis**
Update comment about  about (web|public)/var

### CODE REVIEW

**Comment by adriendupuis** [comment]
> Good catch. Could you re-target & rebase it to `3.0`? (or `3.1` since 3.0 is past EOM - up to you)

@alongosz Let say 3.0 in case there is a last 3.0.7. There is no conflict with 3.0 nor 3.1 so it should be easy to propagate upward.

**Comment by adriendupuis** [comment]
> > Good catch. Could you re-target & rebase it to `3.0`? (or `3.1` since 3.0 is past EOM - up to you)
> 
> @alongosz Let say 3.0 in case there is a last 3.0.7. There is no conflict with 3.0 nor 3.1 so it should be easy to propagate upward.

No, there is some files that want to come with. I got to do the rebase. Sorry for the too early ping.

**Comment by adriendupuis** [comment]
> > > Good catch. Could you re-target & rebase it to `3.0`? (or `3.1` since 3.0 is past EOM - up to you)
> > 
> > 
> > @alongosz Let say 3.0 in case there is a last 3.0.7. There is no conflict with 3.0 nor 3.1 so it should be easy to propagate upward.
> 
> No, there is some files that want to come with. I got to do the rebase. Sorry for the too early ping.

@alongosz Rebased on 3.0.

**Comment by adriendupuis** [comment]
@alongosz I properly rebased this PR on 3.1 this time.

**Comment by lserwatka** [comment]
@adamwojs could you merge it up?

**Pull request merged**
