### PR TITLE
Fix EZP-25638: Editing content types when default siteaccess only uses nor-NO as language

### PR DESCRIPTION
**Pull request by glye**
> Doc fix for https://jira.ez.no/browse/EZP-25638
> Status: Ready for review

In the immortal words of Boromir: "One does not simply remove eng-GB from the site languages list."

### CODE REVIEW

**Comment by andrerom** [comment]
+1 however should we be doing something more here as well? _(better error reporting in UI, clear way for how to manage to remove a locale, ..)_

**Comment by yannickroger** [comment]
+1

**Comment by glye** [comment]
> better error reporting in UI

Yes, I can add a story for showing error when no data found in specified language

> clear way for how to manage to remove a locale

I wouldn't doc that unless we add proper functionality for it, since right now it means doing lots of manual, error-prone sql queries.

> add support in installer for selecting language to install in

Yes, I'll add a story for that too.

**Comment by andrerom** [comment]
>> better error reporting in UI
> Yes, I can add a story for showing error when no data found in specified language

or UI should detect this. could you ping me on skype with info on where this fails?


>> clear way for how to manage to remove a locale
> I wouldn't doc that unless we add proper functionality for it, since right now it means doing lots of manual, error-prone sql queries.

I was thinking of either a command or something to remove a locale, not manual sql queries.
The language UI should also refuse to delete a language if in use as well if it doesn't already.

>> add support in installer for selecting language to install in
> Yes, I'll add a story for that too.

Note that there probably is one already for improving installer.

**Comment by glye** [comment]
> The language UI should also refuse to delete a language if in use as well if it doesn't already

It does, this seems ok: `Argument 'language' is invalid: Deleting language logic error, some content still references that language and therefore it can't be deleted`

**Comment by andrerom** [comment]
ok, well merging this one and make sure the other enhancement on content type language is handled as part of this issue before sending to QA _(for instance change it to a sub task)_.

**Pull request merged**
