### PR TITLE
Behat imports + PlatformBehatBundle routing

### PR DESCRIPTION
**Pull request by bdunogier**
This PR tries to move behat profile & suite for core to a `behat.yml` file inside `vendor/ezsystems/ezpublish-kernel/eZ/Bundles/EzPublishCoreBundle`, with an import in ezplatform's `behat.yml`.

It would allow PR authors to add scenarii without having to open a PR. Furthermore, it, I think, makes more sense since the Behat feature + context config is in the same repository than the actual tested feature.

The PR also adds a `routing_behat.yml` file, so that we can load the routes defined in The `PlatformBehatBundle` inside the kernel.

### TODO
- [ ] Rebase, removing the behat.yml imports commit

### CODE REVIEW

**Comment by bdunogier** [comment]
Ping @miguelcleverti @andrerom.

**Comment by bdunogier** [comment]
The failure is a known one from the refactoring.

**Comment by miguelcleverti** [comment]
+1

**Comment by andrerom** [comment]
+1

**Comment by bdunogier** [comment]
The part about behat.yml and imports has been merged in another PR.

**Comment by andrerom** [comment]
close?

**Comment by bdunogier** [comment]
yep

**Pull request closed without merging**
