### PR TITLE
[Behat] Add testing of platform-ui

### PR DESCRIPTION
**Pull request by andrerom**
- [x] Successful run
- [ ] Updates to get behat tests to pass

### CODE REVIEW

**Comment by andrerom** [comment]
@ezsystems/qa-team behat failures: https://travis-ci.org/ezsystems/ezplatform/jobs/82647450

**Comment by andrerom** [comment]
Stuck on this, @vidarl is going alternative route on setting up testing on ci using docker. bonus will be more control over environment as it can more easily be executed locally if needed.

**Comment by andrerom** [comment]
Closing as we got it working with ezci (ez.yml)

**Comment by bdunogier** [comment]
It is still open, @andrerom, forgot to click on Close ? :-)

**Comment by andrerom** [comment]
yes :)

**Pull request closed without merging**
