### PR TITLE
Fixed nginx config, broken by PR #70 ( Renamed 'ezpublish' to 'app' )

### PR DESCRIPTION
**Pull request by vidarl**

### CODE REVIEW

**Comment by bdunogier** [comment]
+1

**Comment by vidarl** [comment]
Commit message updated...

**Comment by bdunogier** [comment]
Thank you @vidarl.

**Comment by andrerom** [comment]
did anyone grep for "index"? I searched for use of "index.php" but forgot to search for escaped variant basically.

**Comment by bdunogier** [comment]
No, I did not. I mainly cared about the "getting it to work" part.

**Pull request merged**
