### PR TITLE
EZP-25974: Reduce parameters user is asked about on install

### PR DESCRIPTION
**Pull request by andrerom**
https://jira.ez.no/browse/EZP-25974

To simplify install, move parameters that aren't so common to setup on first install to default parameters file.

- [x] Handle ~~by doc or~~ by config to not wipe out old config settings on upgrade: https://github.com/Incenteev/ParameterHandler#keeping-outdated-parameters

### CODE REVIEW

**Comment by bdunogier** [comment]
I'd go for the "keep outdated" option, at least for the time being. Deprecate the outdated parameters, and remove them in a major version.

**Comment by andrerom** [comment]
Ok, review ping @bdunogier @lserwatka

**Comment by lserwatka** [comment]
Looks good to me +1

**Comment by lserwatka** [comment]
@andrerom do you aim this PR for 1.4.0 final?

**Comment by andrerom** [comment]
yes :)

**Pull request merged**
