### PR TITLE
Use SYMFONY_ENV for consistency

### PR DESCRIPTION
**Pull request by xrow**
The name of the environment variable isn't consistent. Renaming all occurences to SYMFONY_ENV.

### CODE REVIEW

**Comment by andrerom** [comment]
consistency with what? This will have to be changed several places, including apache doc.

**Comment by xrow** [comment]
Please look in ezpublish/console. They should be the same from my point of view. I guess you also need to update documentation.

**Comment by andrerom** [comment]
Good point, ok we should look into this then before/during beta, could make sense to do this together with renaming of `ezpublish` folder and so some other intended restructuring.

**Comment by andrerom** [comment]
Handled in #70

**Comment by xrow** [comment]
Thanks for the support.

**Pull request closed without merging**
