### PR TITLE
Added build argument DISTRIBUTION_IMAGE to Dockerfile-distribution

### PR DESCRIPTION
**Pull request by vidarl**
This PR makes it possible to change COMPOSE_PROJECT_NAME without altering doc/docker/Dockerfile-distribution.

Instead you may use docker build argument as documented  in README

### CODE REVIEW

**Comment by vidarl** [comment]
It applies fine on 1.7 so set that as base. May set base to 1.13 if you prefer

**Comment by vidarl** [comment]
This one has not been merged to 1.13 on ezplatform-demo, ezplatform-ee-demo yet. Could someone fix that?

**Comment by andrerom** [comment]
> This one has not been merged to 1.13 on ezplatform-demo, ezplatform-ee-demo yet. Could someone fix that?

feel free to handle it. be aware when merging from ezplatform-ee:1.13 to ezplatform-ee-demo:1.13 that you don't merge that up to ezplatform-ee-demo:2.x, that git flow is not maintained by web team so it's just a big conflict.

**Comment by vidarl** [comment]
> feel free to handle it. be aware when merging from ezplatform-ee:1.13 to ezplatform-ee-demo:1.13 that you don't merge that up to ezplatform-ee-demo:2.x, that git flow is not maintained by web team so it's just a big conflict.

Ok, done

**Pull request merged**
