### PR TITLE
[Travis] Switch to Trusty infra

### PR DESCRIPTION
**Pull request by andrerom**
for:
- possible faster execution
- more stable _(less mysql/postgres/solr gone issues)_

### CODE REVIEW

**Comment by bdunogier** [comment]
The Travis error comes from an issue with the create session HTTP request. Can't say why (yet), but the object that is parsed from the HTTP response (`$this->getResponseObject()` in the REST authentication subcontext is obviously not a `Session`, hence the error.

We could at the very least check the type of object we get as a Response, and provide better feedback if it is not a session.

**Comment by andrerom** [comment]
Closing in favour of #97, will 


@bdunogier What is gitcloney? _(see checks)_

**Comment by bdunogier** [comment]
gitcloney might be an aging actor that sells overpriced coffee.

[gitcolony.com](gitcolony.com) on the other hand is a review-request thing that sits on top of github. Stumbled upon it while browsing the git integration directory, looked promising. Gave it a try, but disabled it for now.

**Comment by andrerom** [comment]
Duno, it ran at some point on this PR.

**Comment by bdunogier** [comment]
It was active for maybe half an hour.

**Comment by andrerom** [comment]
Repos/forks on own account? :)
*I don't mind us trying services, was just not aware this one was tested*

**Pull request closed without merging**
