### PR TITLE
EZP-28336 : app/config/env/docker.php is actually non-docker specific

### PR DESCRIPTION
**Pull request by vidarl**
This PR does the following:
- renames app/config/env/docker.php → app/config/env/generic.php as the file contains no docker specific stuff.
- adds possibility to set purge_type via environment variable HTTPCACHE_PURGE_TYPE
- adds possibility to set recommendation settings via environment variables

Note:
When merging this to ezplatform-ee-demo, please note that the recommencation settings are already in docker.php (generic.php) ... Make sure that code is not duplicated, and that is is located  at the same spot in the file to avoid further merge conflicts.

### CODE REVIEW

**Comment by andrerom** [comment]
Missing issue and such, but +1

**Comment by vidarl** [comment]
Added jira issue : https://jira.ez.no/browse/EZP-28336 as requested

**Comment by vidarl** [comment]
so, do we have a 1.13 branch which this one can be merged to ?

**Comment by vidarl** [comment]
well, there is no BC so I guess it may also be merged to master

**Comment by andrerom** [comment]
This should go into 1.13 if there is a branch for that, it will then go into 1.13 -> master -> 2.0 _(if still separate branch)_

**Pull request merged**
