### PR TITLE
Changed console path in assetic comment

### PR DESCRIPTION
**Pull request by kmadejski**
This PR fixes path to Symfony's console stated  in the comment in Apache vhost template.

### CODE REVIEW

**Comment by lserwatka** [comment]
Is 2.2 branch affected as well by this change?

**Comment by kmadejski** [comment]
@lserwatka yes. I've changed base to 2.2. I'll rebase it soon.

**Comment by andrerom** [comment]
@kmadejski can you also fix README.md? And also nginx? _(README and template)_

**Comment by kmadejski** [comment]
This PR has been rebased due to the failing tests.

**Pull request merged**
