### PR TITLE
Use global namespaces in EzPublishKernel

### PR DESCRIPTION
**Pull request by joaoinacio**
See ~~https://github.com/ezsystems/ezpublish-community/pull/172~~ [ezpublish-community/pull/243](https://github.com/ezsystems/ezpublish-community/pull/243)

### CODE REVIEW

**Comment by andrerom** [comment]
+1 from my side, just trying to think if there is anything but LegacyBridge install instructions we need to update. ping @bdunogier @lolautruche

**Comment by joaoinacio** [comment]
@andrerom : actually, AFAICT the docs are already OK:
```
Edit ezpublish/EzPublishKernel.php, and add
 new eZ\Bundle\EzPublishLegacyBundle\EzPublishLegacyBundle( $this ) 
at the end of the $bundles array. 
```

**Comment by bdunogier** [comment]
+1 :fire:

**Comment by lolautruche** [comment]
+1

**Pull request merged**
