### PR TITLE
[Insight] Symfony secret should be changed

### PR DESCRIPTION
**Pull request by SylvainGuittard**
jira issue: https://jira.ez.no/browse/EZP-26287

Form SensioLabsInsight:

> Symfony secret should be changed
> The secret is the default one from the Symfony Standard Edition

### CODE REVIEW

**Comment by andrerom** [comment]
Hmm, as end user is the one that needs to change it I'm not sure I agree with this one. But of course we could change to any other kind of sentence that says user should change it asap.

**Comment by SylvainGuittard** [comment]
Updated ;)

**Comment by andrerom** [comment]
+1

**Comment by yannickroger** [comment]
+1
(I thought you would propose something with a joke as a token @SylvainGuittard  :smile: )

**Pull request merged**
