### PR TITLE
 [DO NOT MERGE] update PlatformUI behat tests

### PR DESCRIPTION
**Pull request by miguelcleverti**
DO NOT MERGE

### CODE REVIEW

**Comment by andrerom** [comment]
You are testing branch (mine) on ezsystems repo and not your own.

**Comment by andrerom** [comment]
See https://getcomposer.org/doc/04-schema.md#repositories

**Comment by andrerom** [comment]
I got a  bit further by fixing the spin function and increasing the timing functions:
https://github.com/ezsystems/PlatformUIBundle/commit/421c1467ef608a7e28e4f0b92e1c2af2b57c7a3c

Result is that it almost passes:
https://travis-ci.org/ezsystems/ezplatform/jobs/85624461

Disabling symfony debug (891286aeba4ffafecbd9fa05667a3fa5d1260e7d) helped a bit speeding it up, so this is what I got with that:
https://travis-ci.org/ezsystems/ezplatform/jobs/85622603

However it is unstable, so maybe I did not progress at all :/
https://travis-ci.org/ezsystems/ezplatform/jobs/85629387

**Comment by joaoinacio** [comment]
"standard" suite looking good @ https://travis-ci.org/ezsystems/ezplatform/jobs/85735948 
"CopyMoveDelete" failing due to broken kernel validators

**Comment by andrerom** [comment]
Great :) Fantastic work guys!
Rerunning it now to double check, and we should run it after noon monday to check, but in the meantime I guess you can open new branch where commits are cleaned up so we get this in :)

**Comment by bdunogier** [comment]
So this overall means that we can't enable debugging in any behat test, right ?

**Comment by joaoinacio** [comment]
It looked like there is still something strange happening with treeview node selection/expanding,
tesing again with some optimization and forced wait for the 'loading' spinner'. 
The UDW's confirm/removal buttons are related to this as well.

**Comment by andrerom** [comment]
> So this means that we can't enable debugging in any behat test, right ?

Context? Are you talking about the other PR where I disabled debug? afaik nothing on that here.

**Comment by bdunogier** [comment]
> Context ?

This context: "Disabling symfony debug (891286a) helped a bit speeding it up, so this is what I got with that: https://travis-ci.org/ezsystems/ezplatform/jobs/85622603"

**Comment by andrerom** [comment]
> This context: "Disabling symfony debug (891286a) helped a bit speeding it up, so this is what I got with that: https://travis-ci.org/ezsystems/ezplatform/jobs/85622603"

ok, but that is #46 :)

**Comment by joaoinacio** [comment]
Finally, after a LOT of testing fails, the treeview problem has been identified, I believe:

The vhost config for the behat env sets `USE_DEBUGGING=1`, which causes the css to be generated in "parts". what happens is, they are dumped for prod on install (and later behat) envs. without debugging.

This causes travis to test the website without some important CSS files, which results in selenium not being able to find visible elements to click...
ping @andrerom

**Comment by joaoinacio** [comment]
Last problem seems to be resolved, which was the modal "Confirm dialog" being kept open when executing the proceeding test, causing it to fail.
Fixed by detecting an open dialog (and closing it) @afterScenario

**Comment by miguelcleverti** [comment]
No longer needed

**Pull request closed without merging**
