### PR TITLE
Remove notices and deprecated warnings in dev

### PR DESCRIPTION
**Pull request by gadelkareem**

### CODE REVIEW

**Comment by emodric** [comment]
Why would you want to do that?

**Comment by gadelkareem** [comment]
the deprecated errors are breaking the UI

**Comment by emodric** [comment]
I haven't experienced that. In any case, disabling deprecations and notices is hardly a solution.

**Comment by alongosz** [comment]
If this is breaking your UI, please configure your web server to log warnings and deprecations instead of displaying them. Additionaly if those notices, warnings, and deprecations come from eZ Platform Core itself, the proper approach is to fix the source of each message, not make it silent.
Closing as "won't fix".

**Pull request closed without merging**
